### ISSUE TITLE
Add a React Fragment to enclose list of tasks

### ISSUE THREAD

**Issue by ayushvj08** [pupilfirst/wd301-scripts#222]
In Level 3, [State initialization through constructor lesson](class-components/state-in-class-components/README.md) we should add an enclosing react fragment while rendering the list of tasks.
https://github.com/pupilfirst/wd301-scripts/blob/d5fa214bddf68d1e529758b131b0f0a9c214f937/class-components/state-in-class-components/README.md?plain=1#L146

- So, the final code looks like this 👇
```
class TaskList extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      tasks: [{ title: "Pay rent" }, { title: "Submit assignment" }],
    };
  }

  render() {
    return (
      <>
        {this.state.tasks.map((task) => (
          <Task title={task.title} />
        ))}
      </>
    );
  }
}
```

**Comment by reenas** [comment]
@developedbysaad Check this and include as needed

**Comment by reenas** [comment]
I have edited this
